-- MMC Central seed data (categories + products)
-- Generated from src/data/menu.json
-- Note: legacy_id = product id inside each category (matches site URLs)

TRUNCATE public.products RESTART IDENTITY;
TRUNCATE public.categories RESTART IDENTITY CASCADE;

INSERT INTO public.categories (id, name, slug, icon, description, sort_order, is_active) VALUES
  (1, 'PASTRY', 'pastry', 'cake', 'Cakes, Tarts, Muffins, Cookies & more', 1, true),
  (2, 'BAKERY', 'bakery', 'croissant', 'Croissants, Sourdough, Breads & Pastries', 2, true),
  (3, 'COLD KITCHEN', 'cold-kitchen', 'bowl-food', 'Fresh Fruits & Cold Platters', 3, true),
  (4, 'SALAD', 'salads', 'leaf', 'Fresh & Wholesome Salads', 4, true),
  (5, 'SANDWICH', 'sandwiches', 'sandwich', 'Sandwiches, Wraps & Bagels', 5, true),
  (6, 'SOUPS', 'soups', 'bowl-steam', 'Freshly Made Hot Soups', 6, true),
  (7, 'JUICES', 'juices', 'glass-water', 'Natural Fresh Juices', 7, true);

SELECT setval(pg_get_serial_sequence('public.categories', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.categories));

INSERT INTO public.products (category_id, legacy_id, name, price, weight, image, hover_image, description, available, sort_order) VALUES
  (1, 1, 'TIRAMISU GATHERING', 6.65, '1.2 KG', NULL, NULL, NULL, true, 1),
  (1, 2, 'TIRAMISU MINI', 1.45, '250 GR', NULL, NULL, NULL, true, 2),
  (1, 3, 'PECAN TART GATHERING', 14.25, '1.75 KG', NULL, NULL, NULL, true, 3),
  (1, 4, 'PECAN TART MINI', 0.85, '100 GR', NULL, NULL, NULL, true, 4),
  (1, 5, 'APPLE PIE', 4.25, '1.750 KG', NULL, NULL, NULL, true, 5),
  (1, 6, 'APPLE PIE MINI', 0.6, '120 GR', NULL, NULL, NULL, true, 6),
  (1, 7, 'MILK CHOCOLATE COOKIES', 0.45, '80 GR', NULL, NULL, NULL, true, 7),
  (1, 8, 'RED VELVET COOKIES', 0.6, NULL, NULL, NULL, NULL, true, 8),
  (1, 9, 'MATCHA COOKIES', 0.75, NULL, NULL, NULL, NULL, true, 9),
  (1, 10, 'DOUBLE CHOCOLATE COOKIES', 0.6, '80 GR', NULL, NULL, NULL, true, 10),
  (1, 11, 'STRAWBERRY BREAKFAST MUFFIN', 0.75, 'Crammed with Walnuts, dusted with Oat flakes and filled with a strawberry compote.', NULL, NULL, 'Crammed with Walnuts, dusted with Oat flakes and filled with a strawberry compote.', true, 11),
  (1, 12, 'ORANGE & COCONUT MUFFIN', 0.75, 'Infused with zesty orange peel and topped with flaked coconut.', NULL, NULL, 'Infused with zesty orange peel and topped with flaked coconut.', true, 12),
  (1, 13, 'DOUBLE CHOCOLATE MUFFIN', 0.75, NULL, NULL, NULL, NULL, true, 13),
  (1, 14, 'BLUEBERRY MUFFIN', 0.75, NULL, NULL, NULL, NULL, true, 14),
  (1, 15, 'CHOCOLATE CAKE GATHERING', 10.65, '1.143 KG', NULL, NULL, NULL, true, 15),
  (1, 16, 'SAFFRON MILK CAKE GATHERING', 4, '1 KG', NULL, NULL, NULL, true, 16),
  (1, 17, 'RED VELVET CAKE GATHERING', 6.85, '1.2 KG', NULL, NULL, NULL, true, 17),
  (1, 18, 'SAN SEBASTIAN CHEESECAKE GATHERING', 6.5, '1.145 KG', NULL, NULL, NULL, true, 18),
  (1, 19, 'SAN SEBASTIAN CHEESECAKE MINI', 0.85, '150 GR', NULL, NULL, NULL, true, 19),
  (1, 20, 'LOTUS BISCOFF CHEESECAKE', 12.85, '1.680 KG', NULL, NULL, NULL, true, 20),
  (1, 21, 'CARROT CAKE MINI', 0.28, '85 GR', NULL, NULL, NULL, true, 21),
  (1, 22, 'CARROT CAKE LOAF', 4, '1 KG', NULL, NULL, NULL, true, 22),
  (1, 23, 'MAPLE BUTTERNUT & PECAN CAKE MINI', 0.28, '85 GR', NULL, NULL, NULL, true, 23),
  (1, 24, 'MAPLE BUTTERNUT & PECAN CAKE LOAF', 4, '1 KG', NULL, NULL, NULL, true, 24),
  (1, 25, 'ORANGE  & POLENTA MINI', 0.28, '85 GR', NULL, NULL, NULL, true, 25),
  (1, 26, 'ORANGE  & POLENTA CAKE LOAF', 4, '1 KG', NULL, NULL, NULL, true, 26),
  (1, 27, 'CINNAMON & CREAM MINI', 0.28, '85 GR', NULL, NULL, NULL, true, 27),
  (1, 28, 'CINNAMON & CREAM LOAF', 4, '1 KG', NULL, NULL, NULL, true, 28),
  (1, 29, 'MARBLE CAKE', 4, '1 KG', NULL, NULL, NULL, true, 29),
  (1, 30, 'CHOCOLATE BROOKIES', 9.7, '1.395 KG', NULL, NULL, NULL, true, 30),
  (1, 31, 'CINNAMON ROLL PUDDING', 7.35, '1.265 KG', NULL, NULL, NULL, true, 31),
  (1, 32, 'SALTED CARAMEL BROWNIE TRAY 12 PCS', 9.1, '1.2 KG', NULL, NULL, NULL, true, 32),
  (2, 1, 'PLAIN CROISSANT', 0.45, '75 GR', NULL, NULL, NULL, true, 1),
  (2, 2, 'CHEESE CROISSANT', 0.6, '115 GR', NULL, NULL, NULL, true, 2),
  (2, 3, 'TURKEY & CHEESE CROISSANT', 0.55, '115 GR', NULL, NULL, NULL, true, 3),
  (2, 4, 'CHEESE HALLOUMI CROISSANT', 1, '200 GR', NULL, NULL, NULL, true, 4),
  (2, 5, 'PISTACHIO CROISSANT', 1, '115 GR', NULL, NULL, NULL, true, 5),
  (2, 6, 'ALMOND CROISSANT', 0.6, '135 GR', NULL, NULL, NULL, true, 6),
  (2, 7, 'PAIN AU CHOCOLAT', 0.75, '105 GR', NULL, NULL, NULL, true, 7),
  (2, 8, 'ALMOND PAIN AU CHOCOLAT', 0.75, '105 GR', NULL, NULL, NULL, true, 8),
  (2, 9, 'BLACKBERRY DANISH', 1.1, '151 GR', NULL, NULL, NULL, true, 9),
  (2, 10, 'APRICOT DANISH', 1.1, '151 GR', NULL, NULL, NULL, true, 10),
  (2, 11, 'CINNAMON BUN', 0.5, '75 GR', NULL, NULL, NULL, true, 11),
  (2, 12, 'CLASSIC BUN', 0.2, '100 GR', NULL, NULL, NULL, true, 12),
  (2, 13, 'POTATO BUN', 0.1, '50 GR', NULL, NULL, NULL, true, 13),
  (2, 14, 'GOLDEN BRIOCHE BUN', 0.25, '77 GR', NULL, NULL, NULL, true, 14),
  (2, 15, 'NEW COUNTRY SOURDOUGH - 42OGR', 0.45, NULL, NULL, NULL, NULL, true, 15),
  (2, 16, 'NEW COUNTRY SOURDOUGH - 850GR', 0.9, NULL, NULL, NULL, NULL, true, 16),
  (2, 17, 'OLIVE SOURDOUGH - 480GR', 0.95, NULL, NULL, NULL, NULL, true, 17),
  (2, 18, 'OLIVE SOFT CRUST SOURDOUGH - 540GR', 1, NULL, NULL, NULL, NULL, true, 18),
  (2, 19, 'MULTICEARAL SOURDOUGH - 485GR', 1.1, NULL, NULL, NULL, NULL, true, 19),
  (2, 20, 'BAGUETTE SOURDOUGH - 275GR', 0.35, NULL, NULL, NULL, NULL, true, 20),
  (2, 21, 'MULTICEREAL BAGUETTE SOURDOUGH - 275GR', 0.5, NULL, NULL, NULL, NULL, true, 21),
  (2, 22, 'OLIVE BAGUETTE SOURDOUGH - 275GR', 0.65, NULL, NULL, NULL, NULL, true, 22),
  (2, 23, 'WHITE TOAST LOAF', 1.75, '1.450 KG', NULL, NULL, NULL, true, 23),
  (2, 24, 'BRIOCHE TOAST LOAF', 4.5, '1.440 KG', NULL, NULL, NULL, true, 24),
  (2, 25, 'CROUTONS', 1.65, '500 GR', NULL, NULL, NULL, true, 25),
  (2, 26, 'BREAD CRUMBS', 1.65, '500 GR', NULL, NULL, NULL, true, 26),
  (2, 27, 'BREAD BOWL', 0.65, NULL, NULL, NULL, NULL, true, 27),
  (2, 28, 'FOCACCIA BREAD TRAY', 0.75, '1.460 KG', NULL, NULL, NULL, true, 28),
  (2, 29, 'PIZZA PEPPERONI', 1.5, '410 GR', NULL, NULL, NULL, true, 29),
  (2, 30, 'PIZZA MARGHERITA', 1.25, '375 GR', NULL, NULL, NULL, true, 30),
  (2, 31, 'ARABIC CHEESE FATAYER', 0.28, '87 GR', NULL, NULL, NULL, true, 31),
  (2, 32, 'LABNAH CHEESE FATAYER', 0.2, '82 GR', NULL, NULL, NULL, true, 32),
  (2, 33, 'ZAATAR FATAYER', 0.3, '103 GR', NULL, NULL, NULL, true, 33),
  (2, 34, 'CHEESE & TOMATO FATAYER', 0.35, '96 GR', NULL, NULL, NULL, true, 34),
  (2, 35, 'SPINACH FATAYER', 0.2, '96 GR', NULL, NULL, NULL, true, 35),
  (2, 36, 'CIABATTA BREAD', 0.1, '70 GR', NULL, NULL, NULL, true, 36),
  (2, 37, 'PANINI BREAD', 0.1, '45 GR', NULL, NULL, NULL, true, 37),
  (2, 38, 'CHEESE BREADSTICKS', 1.6, '500 GR', NULL, NULL, NULL, true, 38),
  (2, 39, 'SESAME BREADSTICKS', 0.8, '500 GR', NULL, NULL, NULL, true, 39),
  (2, 40, 'ZAATAT BREADSTICKS', 1.35, '500 GR', NULL, NULL, NULL, true, 40),
  (2, 41, 'PLAIN BREADSTICKS', 0.45, '500 GR', NULL, NULL, NULL, true, 41),
  (2, 42, 'PLAIN BAGEL', 0.1, '65 GR', NULL, NULL, NULL, true, 42),
  (2, 43, 'MULTICEARAL BAGEL', 0.12, '65 GR', NULL, NULL, NULL, true, 43),
  (2, 44, 'SIMIT BREAD', 0.25, NULL, NULL, NULL, NULL, true, 44),
  (2, 45, 'SPANISH BREAD', 0.25, NULL, NULL, NULL, NULL, true, 45),
  (2, 46, 'SPINACH CHEESE PRETZEL', 0.6, '11G GR', NULL, NULL, NULL, true, 46),
  (2, 47, 'TURKEY CHEESE PRETZEL', 0.65, '120 GR', NULL, NULL, NULL, true, 47),
  (2, 48, 'CHEESE TOMATO DANISH', 0.45, '95 GR', NULL, NULL, NULL, true, 48),
  (2, 49, 'CHOCOLATE TWISTER', 0.8, '120 GR', NULL, NULL, NULL, true, 49),
  (3, 1, 'WATERMELON CUBES', 0.65, '500 GR', NULL, NULL, NULL, true, 1),
  (3, 2, 'SWEETMELON CUBES', 1.55, '500 GR', NULL, NULL, NULL, true, 2),
  (3, 3, 'POMEGRANATE SEEDS', 3.95, '500 GR', NULL, NULL, NULL, true, 3),
  (3, 4, 'MANGO CUBES', 3.55, '500 GR', NULL, NULL, NULL, true, 4),
  (4, 1, 'GREEK CHEESE & CAPERS SALAD', 1.05, NULL, NULL, NULL, NULL, true, 1),
  (4, 2, 'KALE SALAD WITH MAPLE CITRUS DRESSING', 1.2, NULL, NULL, NULL, NULL, true, 2),
  (4, 3, 'CHICKEN CAESAR SALAD', 0.9, NULL, NULL, NULL, NULL, true, 3),
  (4, 4, 'OLIVE FUSILLI PASTA SALAD', 0.9, NULL, NULL, NULL, NULL, true, 4),
  (4, 5, 'EDAMAME LETTUCE SALAD', 0.55, NULL, NULL, NULL, NULL, true, 5),
  (4, 6, 'VEGETABLE NOODLES SALAD', 0.5, NULL, NULL, NULL, NULL, true, 6),
  (5, 1, 'CHICKEN AVOCADO SANDWICH', 0.95, NULL, NULL, NULL, NULL, true, 1),
  (5, 2, 'CLASSIC CLUB SANDWICH', 1.05, NULL, NULL, NULL, NULL, true, 2),
  (5, 3, 'BACON & EGGS SANDWICH', 0.65, NULL, NULL, NULL, NULL, true, 3),
  (5, 4, 'TURKEY CLUB BRIOCHE SANDWICH', 0.55, NULL, NULL, NULL, NULL, true, 4),
  (5, 5, 'BBQ CHICKEN CIABATTA', 0.55, NULL, NULL, NULL, NULL, true, 5),
  (5, 6, 'TURKEY PROTEIN WRAP', 0.75, NULL, NULL, NULL, NULL, true, 6),
  (5, 7, 'CHICKEN CAESAR WRAP', 0.55, NULL, NULL, NULL, NULL, true, 7),
  (5, 8, 'EGG MAYO', 0.8, NULL, NULL, NULL, NULL, true, 8),
  (5, 9, 'GRILLED HALLOUMI ZAATAR CIABATTA', 0.9, NULL, NULL, NULL, NULL, true, 9),
  (5, 10, 'CHICKEN FILLET SANDWICH', 0.55, NULL, NULL, NULL, NULL, true, 10),
  (5, 11, 'FALAFEL WRAP', 0.6, NULL, NULL, NULL, NULL, true, 11),
  (5, 12, 'CHICKEN PESTO WRAP', 0.7, NULL, NULL, NULL, NULL, true, 12),
  (5, 13, 'TURKEY EGG BAGEL', 0.65, NULL, NULL, NULL, NULL, true, 13),
  (6, 1, 'CREAMY TOMATO SOUP', 0.25, '150 GR', NULL, NULL, NULL, true, 1),
  (6, 2, 'GREEN PEAS SOUP', 0.28, '150 GR', NULL, NULL, NULL, true, 2),
  (6, 3, 'PUMPKIN SOUP', 0.28, '150 GR', NULL, NULL, NULL, true, 3),
  (6, 4, 'ZUCCHINI SOUP', 0.25, '150 GR', NULL, NULL, NULL, true, 4),
  (6, 5, 'CELERY CARROT SOUP', 0.2, '150 GR', NULL, NULL, NULL, true, 5),
  (6, 6, 'CAULIFLOWER SOUP', 0.25, '150 GR', NULL, NULL, NULL, true, 6),
  (6, 7, 'GREEN APPLE SOUP', 0.3, '150 GR', NULL, NULL, NULL, true, 7),
  (7, 1, 'MANGO JUICE', 0.6, '500 GR', NULL, NULL, NULL, true, 1),
  (7, 2, 'STRAWBERRY JUICE', 0.55, '500 GR', NULL, NULL, NULL, true, 2),
  (7, 3, 'MIXBERRY JUICE', 3.4, '500 GR', NULL, NULL, NULL, true, 3),
  (7, 4, 'ORANGE JUICE', 0.9, '500 GR', NULL, NULL, NULL, true, 4),
  (7, 5, 'LEMON JUICE', 0.55, '500 GR', NULL, NULL, NULL, true, 5),
  (7, 6, 'CARROT, ORANGE & GINGER JUICE', 1.05, '500 GR', NULL, NULL, NULL, true, 6),
  (7, 7, 'PINEAPPLE STRAWBERRY JUICE', 3.05, '500 GR', NULL, NULL, NULL, true, 7)
ON CONFLICT (category_id, legacy_id) DO UPDATE SET
  name = EXCLUDED.name,
  price = EXCLUDED.price,
  weight = EXCLUDED.weight,
  image = EXCLUDED.image,
  hover_image = EXCLUDED.hover_image,
  description = EXCLUDED.description,
  available = EXCLUDED.available,
  sort_order = EXCLUDED.sort_order;

SELECT setval(pg_get_serial_sequence('public.products', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.products));
